# Generated by Django 2.2.3 on 2019-07-10 04:22

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('abbreviation', models.CharField(max_length=16, unique=True)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MatchPoints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Match points',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initials', models.CharField(max_length=3)),
                ('first_name', models.CharField(max_length=4096)),
                ('last_name', models.CharField(max_length=4096)),
                ('email', models.EmailField(max_length=254)),
                ('ifpa_id', models.IntegerField(blank=True, help_text='Not required', null=True)),
                ('country', django_countries.fields.CountryField(max_length=2)),
            ],
            options={
                'ordering': ['initials'],
            },
        ),
        migrations.CreateModel(
            name='Points',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('points', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Points',
                'ordering': ['points'],
            },
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('name', models.CharField(max_length=255)),
                ('playoffs_are_active', models.BooleanField(default=False)),
                ('playoffs_are_finalized', models.BooleanField(default=False)),
                ('number_of_playoff_matches', models.IntegerField(blank=True, null=True)),
                ('number_of_players_in_a_division', models.IntegerField(blank=True, null=True)),
                ('number_of_players_in_b_division', models.IntegerField(blank=True, null=True)),
                ('playoff_matches_are_created', models.BooleanField(default=False)),
                ('disable_score_registering', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.BigIntegerField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Player')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Tournament')),
            ],
            options={
                'ordering': ['-score'],
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_tiebreaker', models.BooleanField(default=False)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Game')),
                ('player1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='match_player1', to='core.Player')),
                ('player2', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='match_player2', to='core.Player')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Tournament')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='match_winner', to='core.Player')),
            ],
            options={
                'verbose_name_plural': 'Matches',
            },
        ),
    ]
