# Generated by Django 2.2.3 on 2019-07-11 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190711_0843'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='number_of_playoff_matches',
        ),
        migrations.AddField(
            model_name='tournament',
            name='number_of_rounds_against_opponents',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
