# Generated by Django 2.2.3 on 2019-07-12 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_tournament_playoffs_are_finalized'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='division',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
