# Generated by Django 2.2.3 on 2019-07-12 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_game_disable_in_playoffs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='disable_in_playoffs',
        ),
        migrations.AddField(
            model_name='game',
            name='enabled_in_playoffs',
            field=models.BooleanField(default=True),
        ),
    ]
