# Generated by Django 2.2.3 on 2019-07-12 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20190712_0536'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='ipdb_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
