# Generated by Django 2.2.3 on 2019-07-12 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20190712_0628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='is_active_in_playoffs',
            field=models.BooleanField(default=False),
        ),
    ]
