# Generated by Django 2.2.3 on 2019-07-13 01:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20190712_0630'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MatchPoints',
        ),
        migrations.AlterModelOptions(
            name='score',
            options={},
        ),
        migrations.AddField(
            model_name='tournament',
            name='match_points',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='winner',
            field=models.ForeignKey(blank=True, help_text="If you need other options in the select please select Player 1 and Player 2 and click 'Save and continue editing'", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='match_winner', to='core.Player'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='playoff_matches_are_created',
            field=models.BooleanField(default=False, help_text="Don't touch this unless you really know what you are doing"),
        ),
    ]
