# Generated by Django 2.2.3 on 2019-07-13 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20190713_0309'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchpoints',
            name='tournament',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.Tournament'),
            preserve_default=False,
        ),
    ]
