# Generated by Django 2.2.3 on 2019-07-13 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_matchpoints_tournament'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='match_points',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
